### ISSUE TITLE
Keep demo up-to-date with latest release

### ISSUE THREAD

**Issue by wesort** [statamic/demo#1]
[demo.statamic.com/cp]( https://demo.statamic.com/cp) is helpful to explore and test things quickly in a _clean, {s} approved_ environment.

Could I request that it gets the updates as they are released? Perhaps part of it's "reset" script?

For example, currently `demo.statamic.com` is running `4.0.0` and the latest release is `4.2.0`.

**Comment by jasonvarga** [comment]
Good idea.

We can probably make a cron job that'll run `composer update` every night.

(That's not a good idea for real live sites though!)

**Comment by wesort** [comment]
> We can probably make a cron job that'll run `composer update` every night.

A nudge on this.

I'm catching up with reading release notes after a few weeks on holiday, and being able to see them in action instantly is really handy.

**Comment by jackmcdade** [comment]
I got you updated for now, will look at an automated solution shortly!

**Comment by wesort** [comment]
Can I do another nudge on this? I came to test something and demo.statamic.com is on `v4.53.2` currently (22 releases behind). Not urgent, but a useful resource.

Thanks.
